// import { Config } from "./config";
const page_type = document.getElementById("common_config").dataset.pagetype;
// const page_type = "latex";
const boot_body = Config[ENVIRONMENT].Boot_OSS;
const ver_body = Config[ENVIRONMENT].Version;
const js_body = Config[ENVIRONMENT].MainJS[page_type];
document.writeln("<link href='" + boot_body + "/lib/bootstrap-4.3.1-dist/css/bootstrap.min.css' rel='stylesheet' />");
document.writeln("<link href='" + boot_body + "/lib/font-awesome-4.7.0/Font-Awesome-master/css/font-awesome.min.css' rel='stylesheet' />");
document.writeln("  <div id='loading'>");
document.writeln("    <div id='loading-center'>");
document.writeln("      <div id='loading-center-absolute'>");
document.writeln("        <div id='loading-object'></div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </div>");
document.head.removeChild(document.getElementById("common_05"));
